### ISSUE TITLE
task "Check some variables are defined and not empty" not working properly

### ISSUE THREAD

**Issue by pmoscode** [nierdz/ansible-role-nextcloud#48]
The task "Check some variables are defined and not empty" doesn't fail, if the required props are not set.
It took me some time to figure that out.

My role config looked like this before I figured it out:
I <removed> the values of the props.

```
- role: nierdz.nextcloud
    vars:
      nextcloud_domain: <removed>
      nextcloud_admin_user: <removed>
      nextcloud_admin_password: "<removed>"
      nextcloud_dbuser: "<removed>"
      nextcloud_dbpassword: "<removed>"
      nextcloud_datadirectory: <removed>
```

Nextcloud was successfully installed but I got an "internal server error" when I opened the page in browser. 
I tried to search in the logs, but no luck. 
Eventually I checked the Nextcloud "config.php", and there it was. The required fields weren't set.
